<?php
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\Application;
use Bitrix\Main\ModuleManager;
use Bitrix\Main\IO\Directory;
use Bitrix\Main\Loader;

class devconsult_teamtasks extends CModule
{
    public $exclusionFiles = [".","..","menu.php"];

    public function __construct()
    {
        $arModuleVersion = [];
        include __DIR__ . '/version.php';

        $this->MODULE_ID = "devconsult.teamtasks";
        $this->MODULE_NAME = Loc::getMessage("MODULE_NAME");
        $this->MODULE_DESCRIPTION = Loc::getMessage("MODULE_DESCRIPTION");

        $this->MODULE_VERSION = $arModuleVersion['MODULE_VERSION'];
        $this->MODULE_VERSION_DATE = $arModuleVersion['MODULE_VERSION_DATE'];

        $this->MODULE_SORT = 100;

        $this->PARTNER_NAME = Loc::getMessage("PARTNER_NAME");
        $this->PARTNER_URI = Loc::getMessage("PARTNER_URI");
    }

    public function DoInstall()
    {
        if(self::isVersionD7()) {
            ModuleManager::registerModule($this->MODULE_ID);
            $this->InstallFiles();
            $this->InstallDB();
            $this->InstallEvents();
        }
    }

    public function DoUninstall()
    {
        $this->UnInstallEvents();
        $this->UnInstallDB();
        $this->UnInstallFiles();
        ModuleManager::unRegisterModule($this->MODULE_ID);
    }

    public function InstallDB()
    {
        Loader::includeModule($this->MODULE_ID);
        if(!\Bitrix\Main\Application::getConnection()->isTableExists(
            \Devconsult\Teamtasks\Models\TaskTable::getTableName()
        )) {
            \Devconsult\Teamtasks\Models\TaskTable::getEntity()->createDBTable();
        }
    }

    public function UnInstallDB()
    {
        if(Loader::includeModule($this->MODULE_ID)) {
            $entity = \Devconsult\Teamtasks\Models\TaskTable::getEntity();
            $connection = $entity->getConnection();

            $connection->dropTable($entity->getDBTableName());
        }

    }

    public function InstallFiles()
    {
        CopyDirFiles(
            __DIR__ . "/components",
            $_SERVER['DOCUMENT_ROOT'] . "/local/components",
            true,
            true,
        );
    }

    public function UnInstallFiles()
    {
        Directory::deleteDirectory($_SERVER['DOCUMENT_ROOT'] . "/local/components/devconsult/teamtasks.list");
    }

    public function InstallEvents()
    {
        parent::InstallEvents(); // TODO: Change the autogenerated stub
    }

    public function UnInstallEvents()
    {
        parent::UnInstallEvents(); // TODO: Change the autogenerated stub
    }

    public function getPath($notDocumentRoot = false)
    {
        $basePath = dirname(__DIR__); // это абсолютный путь до модуля

        // для Windows заменим обратные слеши на прямые
        if( strtoupper(substr(PHP_OS,0,3)) === "WIN" ) {
            $basePath = str_replace("\\","/",$basePath);    // преобразуем путь в UNIX формат
        }

        // если нужно исключить DocumentRoot
        if( $notDocumentRoot ) {
            $documentRoot = Application::getDocumentRoot();
            if( !empty($documentRoot) && strpos($basePath, $documentRoot) === 0 ) {
                return substr($basePath, strlen($documentRoot));
            }
        }

        return $basePath;
    }

    public function isVersionD7()
    {
        return CheckVersion(ModuleManager::getVersion("main"),"14.00.00");
    }
}